### ISSUE TITLE
Question about the prototype initialization?

### ISSUE THREAD

**Issue by HeimingX** [tfzhou/ProtoSeg#2]
Hi, thanks for the impressive work. 

After reading the paper, I have a question that how the micro-prototypes are initialized? They seem to be properly initialized so as for a reasonable solution in eq.(10). 

Cheers

**Comment by wenguanwang** [comment]
@HeimingX 

The micro-prototypes are randomly initialized. They are essentially cluster centers. Thus they are estimated via an EM fashion: estimate cluster assignments given cluster centers, and update cluster centers with updated cluster assignments.  Or you can also randomly select some data samples (say pixels within the corresponding class) as the micro-prototypes.  For example, in Kmeans, one can randomly select some data as cluster centers or just randomly initialize them. 

Eq. 10 tells you how to get the cluster assignments given certain cluster centers. With the cluster assignments, we need to in turn update the cluster centers. However, due to the drift of the representation (network parameters) during training, we further adopt the momentum strategy for the prototype update.

**Comment by HeimingX** [comment]
Thanks for the convincing response!
